#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source_file="${root_dir}/AGENTS.md"
target_file="${root_dir}/CLAUDE.md"

if [[ ! -f "${source_file}" ]]; then
  echo "Missing source file: ${source_file}" >&2
  exit 1
fi

cat > "${target_file}" <<'EOF'
# Claude Instructions

This file is generated from `AGENTS.md`.
Do not edit this file directly. Update `AGENTS.md`, then run `make sync-agent-docs`.

EOF

cat "${source_file}" >> "${target_file}"

echo "Updated ${target_file}"
